#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: dad88f79-d5a1-4a6d-a261-0f2f9e55c89c
# Source File: GetTextFromChildForm.psproj
#------------------------------------------------------------------------
#region Project Recovery Data (DO NOT MODIFY)
<#RecoveryData:
XAIAAB+LCAAAAAAABACNkk1vgzAMhu+V+h8QdxqoRgdSyGF0VDvsQx3adfKIszEFgkKY2n+/MKBi
6jT1+MT281pW6B4L9YX6uAUDbLlwHPqk1ScW5gcsvqBuS1WzYBVQMsFYy0qJd1vGgUeRuI49HkLg
XcGGe7DeBJ4v1iLGMCyiuKBkbB5Hx5T82CDzKZnjJFeS2ziHzNPaEUZ09ihQY13gA1SYuK5z05WS
J67vsmcD2nTNqmnbIfz/0RSk9O6hrDOlq9emFXPX9G5l4mLZTqo3kFYVzFROqqoKan57MFj3t0zc
XHfosqG7tQnBxQnph7X+te+pcLbwAMMZT2cf6FGX72UNsm/oQ9gOTY4Hk2lVzYWNHaLkrHu5oOTX
b/oGA8oLlFwCAAA=#>
#endregion
<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2016 v5.2.125
     Generated on:       7/20/2016 12:06 PM
     Generated by:        June Blender
     Organization:       SAPIEN Technologies, Inc
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2016
#>


#region Source: Startup.pss
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
TQQAAB+LCAAAAAAABAC9lEtLAzEQgO+C/yH0vOzD7boWdhek0ougxZXqNZvOltA8yiRpyb93W0sV
PYiFhlwyEzIfH8NM9QJMbwH9A7WUDBfDtapHN3E2aq6vCKmeka+4omLGBTxRCU1rKVq3iTfGVMmv
18Ofe2NAdoKDOcRfGd9IwzQK3kVkcWSN43R/IjJ1wjqEWoGzSEVE5m6owR7Bv+o1qLorS1qw4jab
5GNI7yZVcqr6k9J6Y0GGYMRvXC31zsQzjdIEIe47FQaEdMfV6hxWmvdFX/ZZtixSmtO/We9ShHHi
CMxq9C3gljM4q2X/tptqhCB6R6s56kHtAm6n8HO2q+T7+mg+AOzpkf9NBAAA#>
#endregion
#----------------------------------------------
#region Import Assemblies
#----------------------------------------------
[void][Reflection.Assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
[void][Reflection.Assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
[void][Reflection.Assembly]::Load('System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
#endregion Import Assemblies

#Define a Param block to use custom parameters in the project
#Param ($CustomParameter)

function Main {
<#
    .SYNOPSIS
        The Main function starts the project application.
    
    .PARAMETER Commandline
        $Commandline contains the complete argument string passed to the script packager executable.
    
    .NOTES
        Use this function to initialize your script and to call GUI forms.
		
    .NOTES
        To get the console output in the Packager (Forms Engine) use: 
		$ConsoleOutput (Type: System.Collections.ArrayList)
#>
	Param ([String]$Commandline)
		
	#--------------------------------------------------------------------------
	#TODO: Add initialization script here (Load modules and check requirements)
	
	
	#--------------------------------------------------------------------------
	
	if((Call-MainForm_psf) -eq "OK")
	{
		
	}
	
	$global:ExitCode = 0 #Set the exit code for the Packager
}







#endregion Source: Startup.pss

#region Source: MainForm.psf
function Call-MainForm_psf
{
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
VwsAAB+LCAAAAAAABAC9VtFu2jAUfZ+0f7D8HAEBUlopRCrpkKqVURXa7a1ykgv1cGzkOJTs6+eQ
gCjJloAKAhGCz+Hce8+xFfsJfLECmdwRRZD+ElHB+7jdMLHz9QtC9ljSOeWEDSmDHyQEZ0QoHwoZ
NpbRzG4WljOS9xt8hVSyhD6eJJGCsPGT8kC8R42Um30aqGzJQC95Fd1GK30ZyI2ZiiX0OcRKEmag
x9hj1P8OyVQsgPe9Xo9YvnVl3nS60Lq+wYjrUvp4WypG/htlgdRQ7AqupGBR1p6u9VGKJUiV5Jzb
WImJTxjc0RB4WoeGXhnI7NjNLbSKOhIBYGeolSo5LqPA1YT+0YRuu6t1rFYlaUSkHjp2LAPl70pK
6g3eeVcJn8JaZXBUjv+20mXn4AdBAuyMeXpN0Zs1u7m5bPHViUglB2J99lAoreOJdZ1sFOeSeoqd
CcwFoOd77VZ7WfS4SHsQPlG6euyYbQNdFx0+yeMSkp4JZZRrq6cyhhqMLBcHM6nBewISjDlLagvl
EW9p5yyzBn5KvHsewFqPrAy9n780Oe4b4XMICq287i0eRLKZZbJ+QgexUoKfPaDeRma8BO6myTw+
pB/TZrZrx6BEubazZlcfXp3eUc7W2QfZSZTWhDZFlZ9HRd5zBC80igmbqITBgPgLVzAh/53X/UTp
U9lflM7jdbP0nyR9vLmNIgi16xBtsfkviRNGvpCMep+QHLu5+9dDlSyrl9D49P1QrZg+s1xGSJJ3
yuenaLU6M2vWm5lmYLVIh1Rr/QrZZXqiUsdUyGQCckV9OMmyo7tzhYSLtJd3pfe5bu0Mve1us71t
N/cfpJ2/Zui4CFcLAAA=#>
#endregion
	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$MainForm = New-Object 'System.Windows.Forms.Form'
	$textboxMainForm = New-Object 'System.Windows.Forms.TextBox'
	$buttonOpenChildForm = New-Object 'System.Windows.Forms.Button'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$OnLoadFormEvent={
	#TODO: Initialize Form Controls here
	}
	
	$textboxMainForm_TextChanged = {
		#TODO: Place custom script here
	}
	
	$buttonOpenChildForm_Click={
		#TODO: Place custom script here
		$textboxMainForm.Text = ''
		Call-ChildForm_psf
		if ($ChildForm_textboxChildForm -ne '')
		{
			$textboxMainForm.Text = $ChildForm_textboxChildForm
		}		
	}
	
		# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$MainForm.WindowState = $InitialFormWindowState
	}
	
	$Form_StoreValues_Closing=
	{
		#Store the control values
		$script:MainForm_textboxMainForm = $textboxMainForm.Text
	}

	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$textboxMainForm.remove_TextChanged($textboxMainForm_TextChanged)
			$buttonOpenChildForm.remove_Click($buttonOpenChildForm_Click)
			$MainForm.remove_Load($OnLoadFormEvent)
			$MainForm.remove_Load($Form_StateCorrection_Load)
			$MainForm.remove_Closing($Form_StoreValues_Closing)
			$MainForm.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch [Exception]
		{ }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$MainForm.SuspendLayout()
	#
	# MainForm
	#
	$MainForm.Controls.Add($textboxMainForm)
	$MainForm.Controls.Add($buttonOpenChildForm)
	$MainForm.AutoScaleDimensions = '6, 13'
	$MainForm.AutoScaleMode = 'Font'
	$MainForm.ClientSize = '424, 150'
	$MainForm.Margin = '5, 5, 5, 5'
	$MainForm.Name = 'MainForm'
	$MainForm.Text = 'Main Form'
	$MainForm.add_Load($OnLoadFormEvent)
	#
	# textboxMainForm
	#
	$textboxMainForm.Font = 'Segoe UI, 12pt'
	$textboxMainForm.Location = '12, 80'
	$textboxMainForm.Margin = '5, 5, 5, 5'
	$textboxMainForm.Multiline = $True
	$textboxMainForm.Name = 'textboxMainForm'
	$textboxMainForm.ReadOnly = $True
	$textboxMainForm.Size = '400, 51'
	$textboxMainForm.TabIndex = 1
	$textboxMainForm.add_TextChanged($textboxMainForm_TextChanged)
	#
	# buttonOpenChildForm
	#
	$buttonOpenChildForm.Location = '12, 12'
	$buttonOpenChildForm.Name = 'buttonOpenChildForm'
	$buttonOpenChildForm.Size = '144, 37'
	$buttonOpenChildForm.TabIndex = 0
	$buttonOpenChildForm.Text = 'Open Child Form'
	$buttonOpenChildForm.UseVisualStyleBackColor = $True
	$buttonOpenChildForm.add_Click($buttonOpenChildForm_Click)
	$MainForm.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $MainForm.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$MainForm.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$MainForm.add_FormClosed($Form_Cleanup_FormClosed)
	#Store the control values when form is closing
	$MainForm.add_Closing($Form_StoreValues_Closing)
	#Show the Form
	return $MainForm.ShowDialog()

}
#endregion Source: MainForm.psf

#region Source: Globals.ps1
	#--------------------------------------------
	# Declare Global Variables and Functions here
	#--------------------------------------------
	
	
	#Sample function that provides the location of the script
	function Get-ScriptDirectory
	{
	<#
		.SYNOPSIS
			Get-ScriptDirectory returns the proper location of the script.
	
		.OUTPUTS
			System.String
		
		.NOTES
			Returns the correct path within a packaged executable.
	#>
		[OutputType([string])]
		param ()
		if ($hostinvocation -ne $null)
		{
			Split-Path $hostinvocation.MyCommand.path
		}
		else
		{
			Split-Path $script:MyInvocation.MyCommand.Path
		}
	}
	
	#Sample variable that provides the location of the script
	[string]$ScriptDirectory = Get-ScriptDirectory
	
	
	
#endregion Source: Globals.ps1

#region Source: ChildForm.psf
function Call-ChildForm_psf
{
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
wA4AAB+LCAAAAAAABAC9l1tv2jAUx98n7TtYedhTBIRAAQ0ilXSVqpa1AtrtrXKSA3h1bOQ4Ldmn
3wmBXgg0oSsIhHI5f5/b7zihOwRfPoJKzqimBA8iJkXPqFcsw/n6hZDutWJTJig/Zxx+0hAcd8Z4
cC5VWJlHk241dz9TeX/A10Qnc+gZoyTSEFZ+MRHIp6iSarNfk2y7ZZK7VRiNSi39mMSNuY4V9ATE
WlFukpvY48y/hGQsH0D0vFaLNv3midWxG1BrdwwiMJSeMcH1nuM1iJ8eKrQ3XCm0kjzKksSAb5Sc
g9LJSnjq+zDX/VhrKdY2aDWECaDeh5WZtzS4vjRIdb1Qdb3SrpVjLUc+5XDGQhBpmhjEiUksu7x0
IAMwnHPMoVDjcgZCj9hfFNhtG/00aoWitFp9qQJQI53w1BVbQHDGKJfTQvGAKgTCcJomWX1LSBYs
xBD7coG+KI+gWMLEvpKUTsN5g0ShZqSp0jcyYpqlILhYSyyKrwBEoXYMC21k40K2O/vxiOutrK8k
DdKeqnB59T4971aXx2vz4qG6oh7wg08VT72MQAQDiCI6hfcGK1+WK+nTrJpW3SSdXFV2NW7Tawlh
hn3dQgitMo7G1LsQASBR9TLWy/6mERFKwiwooiUZUCa2N3yj5Tib/kM+sfvl9Y3eV7Pml0chjQ6H
4+AwaPTjyUWpXXbbTiOWNZxKILcX2Kb6PL+nvcsQht7Ib50f2pa2iLAojDOBFI1VXAa5jNXNopRm
1W52TGK392LVKuIsRcGdUTGFIB/a/au7/8tc9rw8OHIvT919UDsV/kwqw+lLVOOrxxVMtEmGbDor
Q1z28BtChDEbzvXlXpDWW/jg7ZQBLsNnnWBpbDptpKbMFLxQk38L2LXDfaPh/HupYG4juGNRTPny
taFP/QdX8rTmu4Zny264zr1wF3x7chpFECI9EK1tV1cSJ4x8qTjzPoHAbvV51U0vGfPH8PHpc1Xs
Mf1zcBxHij4xMf2Ir5o9aU5aE8sKmjVq02Jfv0N+nJyYQkylSkagHpkPH2rZ3tm5UsFR0ltlhcON
qR0gt+fTbLa71df/WJ1/DwiHNMAOAAA=#>
#endregion
	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formChildForm = New-Object 'System.Windows.Forms.Form'
	$labelSendMessage = New-Object 'System.Windows.Forms.Label'
	$textboxChildForm = New-Object 'System.Windows.Forms.TextBox'
	$buttonOK = New-Object 'System.Windows.Forms.Button'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$FormEvent_Load={
		$buttonOK.Enabled = $false	
	}
	
	$textboxChildForm_TextChanged={
		#TODO: Place custom script here
		$buttonOK.Enabled = $false
		if ($textboxChildForm.Text -ne '') {
			$buttonOK.Enabled = $true
		}
	}
	
	$buttonOK_Click = {
		#DialogResult = 'OK'
	}
	
	$labelSendMessage_Click = { }	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formChildForm.WindowState = $InitialFormWindowState
	}
	
	$Form_StoreValues_Closing=
	{
		#Store the control values
		$script:ChildForm_textboxChildForm = $textboxChildForm.Text
	}

	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$labelSendMessage.remove_Click($labelSendMessage_Click)
			$textboxChildForm.remove_TextChanged($textboxChildForm_TextChanged)
			$buttonOK.remove_Click($buttonOK_Click)
			$formChildForm.remove_Load($FormEvent_Load)
			$formChildForm.remove_Load($Form_StateCorrection_Load)
			$formChildForm.remove_Closing($Form_StoreValues_Closing)
			$formChildForm.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch [Exception]
		{ }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formChildForm.SuspendLayout()
	#
	# formChildForm
	#
	$formChildForm.Controls.Add($labelSendMessage)
	$formChildForm.Controls.Add($textboxChildForm)
	$formChildForm.Controls.Add($buttonOK)
	$formChildForm.AcceptButton = $buttonOK
	$formChildForm.AutoScaleDimensions = '6, 13'
	$formChildForm.AutoScaleMode = 'Font'
	$formChildForm.ClientSize = '383, 140'
	$formChildForm.FormBorderStyle = 'FixedDialog'
	$formChildForm.Margin = '5, 5, 5, 5'
	$formChildForm.MaximizeBox = $False
	$formChildForm.MinimizeBox = $False
	$formChildForm.Name = 'formChildForm'
	$formChildForm.StartPosition = 'CenterScreen'
	$formChildForm.Text = 'Child Form'
	$formChildForm.add_Load($FormEvent_Load)
	#
	# labelSendMessage
	#
	$labelSendMessage.Location = '12, 9'
	$labelSendMessage.Name = 'labelSendMessage'
	$labelSendMessage.Size = '215, 19'
	$labelSendMessage.TabIndex = 2
	$labelSendMessage.Text = 'Send a message to Main Form'
	$labelSendMessage.add_Click($labelSendMessage_Click)
	#
	# textboxChildForm
	#
	$textboxChildForm.Font = 'Segoe UI, 12pt'
	$textboxChildForm.Location = '10, 43'
	$textboxChildForm.Margin = '5, 5, 5, 5'
	$textboxChildForm.Multiline = $True
	$textboxChildForm.Name = 'textboxChildForm'
	$textboxChildForm.Size = '359, 38'
	$textboxChildForm.TabIndex = 1
	$textboxChildForm.add_TextChanged($textboxChildForm_TextChanged)
	#
	# buttonOK
	#
	$buttonOK.Anchor = 'Bottom, Left, Right'
	$buttonOK.DialogResult = 'OK'
	$buttonOK.Location = '273, 95'
	$buttonOK.Name = 'buttonOK'
	$buttonOK.Size = '98, 33'
	$buttonOK.TabIndex = 0
	$buttonOK.Text = '&OK'
	$buttonOK.UseVisualStyleBackColor = $True
	$buttonOK.add_Click($buttonOK_Click)
	$formChildForm.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formChildForm.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formChildForm.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formChildForm.add_FormClosed($Form_Cleanup_FormClosed)
	#Store the control values when form is closing
	$formChildForm.add_Closing($Form_StoreValues_Closing)
	#Show the Form
	return $formChildForm.ShowDialog()

}
#endregion Source: ChildForm.psf

#Start the application
Main ($CommandLine)
